### ISSUE TITLE
expectations-spy not working as expected

### ISSUE THREAD

**Issue by LittleGnome** [mjwwit/expectations-spy#1] opened 2017-12-18 08:47 UTC
I'm using the following version for my test framework: 
		"expectations": "^0.7.1",
		"expectations-spy": "^0.0.3",
		"istanbul": "^0.4.5",
		"mocha": "^4.0.1"

```require('expectations');
var spyOn = require('expectations-spy').spyOn;
import {clsWebSocketServerUtils} from './web-socket-server-utils';

class clsWebSocketStub
{
  send()
  {
  }
}

describe('The WebSocketServerUtils module', () =>
{
  let lWebSocketStub;

  beforeEach('WebSocketUtils before each', () =>
  {
    lWebSocketStub = new clsWebSocketStub();
  });

  //TODO turn it on when the expectations-spy is working as expected.
  xit('should return the ip address of the web socket', () =>
  {
    const cPongObject = {
      type: 'pong',
      value: 'pong'
    };
    spyOn(lWebSocketStub, 'send');

    clsWebSocketServerUtils.PingAnswer(lWebSocketStub);
    
    // When I wanna use .toHaveBeenCalled(), I get this message the whole time: 
    // unresolved function of method toHaveBeenCalled()
    expect(lWebSocketStub.send).toHaveBeenCalled();
  });
});```

Can you tell me what I'm doing wrong, or is this a know issue?

**Comment by mjwwit** [comment] 2017-12-18 10:00
From what I can see you forgot to import the `expectations` module. Can you try the following code?

```js
require('expectations');
var spyOn = require('expectations-spy').spyOn;
import {clsWebSocketServerUtils} from './web-socket-server-utils';

class clsWebSocketStub
{
  send()
  {
  }
}

describe('The WebSocketServerUtils module', () =>
{
  let lWebSocketStub;

  beforeEach('WebSocketUtils before each', () =>
  {
    lWebSocketStub = new clsWebSocketStub();
  });

  it('should return the ip address of the web socket', () =>
  {
    const cPongObject = {
      type: 'pong',
      value: 'pong'
    };
    spyOn(lWebSocketStub, 'send');

    clsWebSocketServerUtils.PingAnswer(lWebSocketStub);
    
    // When I wanna use .toHaveBeenCalled(), I get this message the whole time: 
    // unresolved function of method toHaveBeenCalled()
    expect(lWebSocketStub.send).toHaveBeenCalled();
  });
});
```

**Comment by LittleGnome** [comment] 2017-12-18 13:13
Sorry for the misunderstanding, but the `require('expectations');` was included only I didn't copied it. Sorry for that. I still have tried it one more time and it is still not working ... :(

**Comment by mjwwit** [comment] 2017-12-18 13:30
Well, I don't think the issue lies in the `expectations-spy` module. I just tried your test file with a simple stub of `clsWebSocketServerUtils`, assuming the `PingAnswer` method actually calls the `send` method of the given websocket it works just fine.

Do you have a repository I can clone to test this?

**Comment by LittleGnome** [comment] 2017-12-18 14:00
The code isn't on a repo that I can give you... But some other thing.
When is do `expect().toHaveBeenCalled` the same issue occurs. Also the autocomplete of the except isn't as I expect it to be.

**Comment by mjwwit** [comment] 2017-12-18 14:09
Autocomplete is handled by the IDE you're using, I can't really influence that...

If you can't give me a repo that contains the issue (this does not have to be your actual repository) I'm afraid I can't help any further. I have tried to reproduce it myself, but the module is working fine for me.

**Comment by mjwwit** [comment] 2017-12-19 07:14
I'm closing this because I'm unable to reproduce the issue. Please re-open if you find a way to reproduce it in a project I can clone.

**Closed as completed by mjwwit** 2017-12-19 07:14 UTC
